// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS-aGaoUtNrKQZh_VPzHTNb-_CtSpwz4c',
    appId: '1:836629613949:web:43cd0eead48abc03e79014',
    messagingSenderId: '836629613949',
    projectId: 'segmentfault-gembo-cd0f7',
    authDomain: 'segmentfault-gembo-cd0f7.firebaseapp.com',
    storageBucket: 'segmentfault-gembo-cd0f7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBokNzXQXyyqMmOHQPypYHZMfba03Cln3Q',
    appId: '1:836629613949:android:1af7e7096332db98e79014',
    messagingSenderId: '836629613949',
    projectId: 'segmentfault-gembo-cd0f7',
    storageBucket: 'segmentfault-gembo-cd0f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHjRLEovX0ArWBclskUYFpns6W4Gano2s',
    appId: '1:836629613949:ios:77c541891b9d33dee79014',
    messagingSenderId: '836629613949',
    projectId: 'segmentfault-gembo-cd0f7',
    storageBucket: 'segmentfault-gembo-cd0f7.appspot.com',
    iosBundleId: 'com.example.userApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHjRLEovX0ArWBclskUYFpns6W4Gano2s',
    appId: '1:836629613949:ios:77c541891b9d33dee79014',
    messagingSenderId: '836629613949',
    projectId: 'segmentfault-gembo-cd0f7',
    storageBucket: 'segmentfault-gembo-cd0f7.appspot.com',
    iosBundleId: 'com.example.userApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS-aGaoUtNrKQZh_VPzHTNb-_CtSpwz4c',
    appId: '1:836629613949:web:2944e39653e6e703e79014',
    messagingSenderId: '836629613949',
    projectId: 'segmentfault-gembo-cd0f7',
    authDomain: 'segmentfault-gembo-cd0f7.firebaseapp.com',
    storageBucket: 'segmentfault-gembo-cd0f7.appspot.com',
  );
}
